import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import "./globals.css";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Giliza Coffee",
  description: "Generated by Giliza Coffee Team",
  applicationName: "Giliza Coffee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} antialiased overflow-x-hidden bg-[#660033]`}
      // style={{
      //   backgroundImage: "url('/images/background/giliza-logo-large.jpg')",
      //   backgroundSize: "cover",
      //   backgroundPosition: "center",
      //   backgroundAttachment: "fixed",
      // }}

      >
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
